# Generated by Django 6.0.5 on 2026-05-22 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, verbose_name='Опис категорії')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Іконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва послуги')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('duration', models.DurationField(verbose_name='Тривалість')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('max_clients', models.PositiveIntegerField(default=1, verbose_name='Макс. кількість клієнтів')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Років досвіду')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основний фахівець')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_specialists', to='services.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Фахівець послуги',
                'verbose_name_plural': 'Фахівці послуг',
            },
        ),
    ]
