# Generated by Django 6.0.5 on 2026-05-22 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespecialist',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_services', to=settings.AUTH_USER_MODEL, verbose_name='Фахівець'),
        ),
        migrations.AddConstraint(
            model_name='servicespecialist',
            constraint=models.UniqueConstraint(fields=('service', 'specialist'), name='unique_service_specialist'),
        ),
    ]
