# Generated by Django 6.0.5 on 2026-05-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_available_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='available_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Порожній список = усі дні тижня', verbose_name='Дні для запису (0=Пн … 6=Нд)'),
        ),
    ]
